### ISSUE TITLE
Algorithm parameter request

### ISSUE THREAD

**Issue by hepengfe** [facebookresearch/CMR#4]
Can you provide some command with hyper-parameters described in the paper?
For example, `experiments/run_scripts/run_simplecl.sh`

**Comment by yuchenlin** [comment]
Sure please look at this file for an example: https://github.com/facebookresearch/CMR/blob/11ca2c9d8735625a26e32b22a1752c41b11edb3c/experiments/run_scripts/slurm_simple.sh
